imp = IJ.getImage();
IJ.run(imp, "Color Balance...", "");
IJ.run(imp, "Enhance Contrast", "saturated=0.35");
IJ.run(imp, "Apply LUT", "");
IJ.run("Close");
imp.setAutoThreshold("Default dark no-reset");
IJ.setRawThreshold(imp, 0, 65535);
IJ.setRawThreshold(imp, 0, 65535);
IJ.setRawThreshold(imp, 0, 200);
IJ.setRawThreshold(imp, 0, 200);
Prefs.blackBackground = true;
IJ.run(imp, "Convert to Mask", "");
IJ.run(imp, "Analyze Particles...", "size=30-120 show=Masks display exclude clear summarize overlay add composite");
IJ.saveAs(imp, "Tiff", "C:/Users/USER001/Downloads/Mask of img_channel000_position000_time000000000_z000 (1).tif");
IJ.saveAs("Results", "C:/Users/USER001/Downloads/Results.csv");
